template_file: "workday_data.xlsx"
output_master: "master_data.xlsx"
hr_dir: "hr_files"
sheets:
  master: "Masterdata_PSteam"
  hiring: "Hiring_data"
  emp: "Employee Master"
  lineup: "LINEUP_PASS_IMPORT"
  permission: "Permission"
skip_rows:
  master: 11
  hiring: 1
  emp: 11
  lineup: 0
  permission: 0
column_mapping:
  Emp id: EID
  Hire Date (DD-MMM-YYYY): DOJ
  FULL_NAME: EMPLOYEE FULL NAME_EN
  Họ tên: EMPLOYEE FULL NAME_VN
  Gender: GENDER
  Giới tính: GENDER
  DOB (DD-MMM-YYYY): DOB
  Dân tộc: ETHNIC
  Nơi sinh: BIRTH PLACE
  'Số CMND/CCCD:': ID CARD
  Ngày cấp CMND/CCCD: ISSUED DATE
  Nơi cấp CCCD/CMND: ISSUED PLACE
  Số CMND Cũ (Nếu Có): OLD ID CARD NO.
  'Địa chỉ thường trú:': PERMANENT ADDRESS
  Địa chỉ tạm trú: TEMPORARY ADDRESS
  Highest Education: EDUCATION
  Marital Status: MARITAL STATUS
  Phone Number: MOBILE PHONE NO
  Email - Work: CNX EMAIL
  Home E-mail address: PERSONAL EMAIL
  Số điện thoại người liên hệ trong trường hợp khẩn cấp: EMERGENCY CONTACT
  Số Bảo Hiểm Xã Hội: SOCIAL INSURANCE NUMBER
  Mã số thuế: PERSONAL TAX CODE
  Số tài khoản ngân hàng nhận lương: BANK ACCOUNT
  Tên ngân hàng: BANK NAME
  Base Pay: BASE SALARY
  Complexity Allowance: COMPLEXCITY ALLOWANCE
  Position Allowance: POSITION ALLOWANCE
  Meal Allowance - Monthly: MEAL ALLOWANCE
  Business Title: BUSINESS_TITLE_EN
  Vị trí: BUSINESS_TITLE_VN
  SUPERVISOR_FULL_NAME: SUPERVISOR
  Career Level: CAREER LEVEL
  Họ và tên chủ hộ: Họ tên chủ hộ
  Giới tính chủ hộ: Giới tính chủ hộ
  Ngày sinh của chủ hộ: DOB chủ hộ
  Mối quan hệ giữa chủ hộ và bạn: Mối quan hệ giữa NLĐ với chủ hộ
  MSA Client: MSA Client
  Contract ID: PROBATION CONTRACT NO
  Process_x: PROJECT
  ORIGINAL_DATE_OF_HIRE: DOJ
  Start Date (DD-MMM-YYYY): FROM
  End Date (DD-MMM-YYYY): TO
  Bệnh viện muốn đăng ký BHYT: HOSPITAL NAME
  Legislation Code / Country: NATIONALITY